Update intermediates-tutorial
smartcontractkit/documentation pull request #1091
Opened 2022-12-05 01:27 UTC by zined1

- No need for sub since Solidity 0.8.0 or can we add Safemath import?
- Mention of "COORDINATOR" in the variables section of the contract.

**IMPORTANT: Please do not create a Pull Request without creating an issue first.Any change needs to be discussed before proceeding.**

## Closing issues

closes #ISSUE_NUMBER_GOES_HERE

...

## Description

...

## Changes

- High level
- changes that
- you made
- ...

2023-01-07 04:18 UTC, thedriftofwords requested changes

2023-01-07 04:18 UTC, thedriftofwords commented on src/pages/getting-started/intermediates-tutorial.md
> +```
Thank you for your contribution! 

Let's add this variable to the existing code block of contract variables at the start of this section, along with an explanation in the bulleted list below that.

To give an example of placement:

```solidity
VRFCoordinatorV2Interface COORDINATOR;
uint64 s_subscriptionId;
address vrfCoordinator = 0x2Ca8E0C643bDe4C2E08ab1fA0da3401AdAD7734D;
bytes32 s_keyHash = 0x79d3d8832d904592c0bf9818b621522c988bb8b0c05cdc3b15aea1b6e8db0c15;
uint32 callbackGasLimit = 40000;
uint16 requestConfirmations = 3;
uint32 numWords =  1;
```

- `VRFCoordinatorV2Interface COORDINATOR`: (_Add explanation here_)
- `uint64 s_subscriptionId`: The subscription ID that this contract uses for funding requests. Initialized in the `constructor`.
...

2024-01-19 20:00 UTC, Spunsd commented
Keep a look out for it!

2024-01-19 20:12 UTC, Spunsd commented
Important

2024-01-23 23:20 UTC, zined1 commented
> Keep a look out for it!

me ?

2024-03-21 16:42 UTC, closed without merging