[Draft] Restructuring billing section
smartcontractkit/documentation pull request #1135
Opened 2023-01-29 06:57 UTC by thedriftofwords

## Description

Create one cohesive billing section on the main page for each VRF method.

2023-03-17 07:54 UTC, dwightjl approved these changes

2023-04-03 23:21 UTC, dwightjl requested changes

2023-04-03 23:21 UTC, dwightjl commented on src/config/sidebar.ts
> +        { title: "Hackathon Resources", url: "resources/hackathon-resources?parent=dataFeeds" },
```suggestion
```

Remove these duplicates.

2023-04-03 23:21 UTC, dwightjl commented on src/pages/vrf/v2/estimating-costs.mdx
> +  + (total gas cost * Wrapper premium)) = total request cost
```suggestion
(Coordinator premium + (total gas cost * Wrapper premium)) = total request cost
```

I think this can be a single line.

2023-04-06 14:53 UTC, thedriftofwords commented
TODO: 

- Resolve conflicts
- Update direct funding example again
- Add/update cross-linking (tutorials, Subscription Manager UI page)
- Add max verification gas back to conceptual section

2023-04-07 00:17 UTC, dwightjl approved these changes

2023-04-12 21:27 UTC, dwightjl approved these changes

2023-04-12 21:28 UTC, merged