Update example-projects.md
smartcontractkit/documentation pull request #114
Opened 2021-05-31 00:18 UTC by gmondok

Added tutorials section.

2021-05-31 02:51 UTC, StephenFluin requested changes
Content looks great! Can you use markdown links instead of `a` tags?

2021-05-31 03:05 UTC, gmondok commented
> Content looks great! Can you use markdown links instead of `a` tags?

I had replicated the same link format that the doc was already using. Do you want me to change all the old links over to markdown links too?

2021-05-31 03:39 UTC, StephenFluin commented
Sure that would be great. We're trying to slowly move the site to more pure
markdown as we touch it more and more.

On Sun, May 30, 2021, 8:05 PM Gage Mondok ***@***.***> wrote:

> Content looks great! Can you use markdown links instead of a tags?
>
> I had replicated the same link format that the doc was already using. Do
> you want me to change all the old links over to markdown links too?
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/smartcontractkit/documentation/pull/114#issuecomment-851134221>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABIJQHUTECGGV4LEXCUBSTTQL4H5ANCNFSM45Z4NDGQ>
> .
>

2021-06-02 15:14 UTC, StephenFluin commented on docs/Additional Information/example-projects.md
> +|**Marine Insurance**|Parametric insurance for the marine industry.|<a href="hhttps://blog.chain.link/build-a-marine-insurance-smart-contract-with-chainlink/" target="_blank" rel="noreferrer, noopene
Typo here in URL as well: 'hhttps'

2021-06-02 23:44 UTC, StephenFluin commented
Can you squash these two commits into one?

```
git reset HEAD~1
git commit -a --amend
git push -f
```

2021-06-03 04:47 UTC, gmondok commented
> Can you squash these two commits into one?
> 
> ```
> git reset HEAD~1
> git commit -a --amend
> git push -f
> ```

Done.

2021-06-03 05:09 UTC, StephenFluin commented
Did the git push -f succeed to your branch?  Not seeing any updates to the PR.

Sorry about the extra steps. We are just trying to keep each PR to one commit to have a nice clean history.

2021-06-03 05:24 UTC, closed without merging