Restructure tasks under node operators
smartcontractkit/documentation pull request #1197
Opened 2023-03-12 02:25 UTC by ritika-b

- consolidates information onto one page
- updates nav

2023-03-30 02:09 UTC, dwightjl commented
Looks like the old URLs need updating.

2023-04-03 23:27 UTC, thedriftofwords requested changes
Simplify/shorten the URLs if we don't need the "task-types" folder anymore. Move the "Writing pipelines" section to become part of the conceptual page on tasks.

2023-04-04 02:34 UTC, thedriftofwords requested changes
Looks good, just a couple more minor edits!

2023-04-04 02:34 UTC, thedriftofwords commented on src/config/sidebar.ts
> +              title: "Pipelines and Task Types",
```suggestion
              title: "Task Types",
```

2023-04-04 02:34 UTC, thedriftofwords commented on src/config/sidebar.ts
> +              title: "Pipelines and Task Types",
For the main "Tasks" page, change the title to "Tasks and pipelines" - to reflect how the content was shifted

2023-04-04 02:34 UTC, thedriftofwords commented on src/pages/chainlink-nodes/oracle-jobs/tasks.md
>  Chainlink has a number of built-in tasks which are listed below. You can also create your own [external adapters](/chainlink-nodes/external-adapters/external-adapters/) for tasks which are accessed t
```suggestion
You can use Chainlink's [built-in tasks](/chainlink-nodes/oracle-jobs/all-tasks), or you can create your own [external adapters](/chainlink-nodes/external-adapters/external-adapters/) for tasks which are accessed through a `bridge`.
```

2023-04-04 02:34 UTC, thedriftofwords commented on src/pages/chainlink-nodes/oracle-jobs/tasks.md
>  Chainlink has a number of built-in tasks which are listed below. You can also create your own [external adapters](/chainlink-nodes/external-adapters/external-adapters/) for tasks which are accessed t
Editing because the tasks are no longer "listed below" in the same way as before; they're all on another page.

2023-04-04 03:38 UTC, dwightjl approved these changes

2023-04-04 18:25 UTC, thedriftofwords approved these changes

2023-04-07 21:21 UTC, merged