Migrate Automation docs to .mdx
smartcontractkit/documentation pull request #1202
Opened 2023-03-15 00:27 UTC by thedriftofwords

2023-03-15 00:28 UTC, thedriftofwords commented
Note: Submit PR #1201 first, then rebase.

2023-03-16 18:24 UTC, dwightjl requested changes

2023-03-16 18:24 UTC, dwightjl commented on src/pages/getting-started/intermediates-tutorial.mdx
> +  <a href="/getting-started/conceptual-overview/#what-is-remix">What is Remix?</a>
This Remix button has CSS issues. This one might be fixed by putting the previous code sample into the code sample component, which has a Remix button by default.

2023-03-16 18:52 UTC, dwightjl commented
Looks like this PR includes duplicate changes with https://github.com/smartcontractkit/documentation/pull/1201/files

Should we close that other PR and just work off of this one?

2023-03-16 22:49 UTC, thedriftofwords commented
Note: Originally I planned to submit PR #1201 with the getting-started changes first, then rebase this one and submit. Now I've rebased this one to remove the getting-started commit so that I can submit it right away, while I try to figure out the issues you pointed out affecting the getting-started pages.

2023-03-17 23:26 UTC, dwightjl approved these changes

2023-03-17 23:27 UTC, merged