Rename tutorials
smartcontractkit/documentation pull request #133
Opened 2021-06-07 06:22 UTC by dmitrydao

fixes #104

2021-06-07 15:29 UTC, PatrickAlphaC requested changes
All the URLs now start with `-`, please address. Let's keep the URLs as they are for now so we don't break anything.

Names are fine. Can we leave on "the basics" on the basics tutorial

2021-06-29 15:57 UTC, StephenFluin commented on docs/Introduction/tutorials/beginners-tutorial.md
> +  title: "Beginners The Basics"
This title doesn't make sense to me? 'Beginners The Basics'?

2021-07-13 15:59 UTC, StephenFluin approved these changes

2021-07-13 16:02 UTC, StephenFluin commented
@PatrickAlphaC Need your approval to merge.

2021-07-19 22:04 UTC, PatrickAlphaC approved these changes

2021-07-19 22:04 UTC, PatrickAlphaC commented
LGTM

2021-07-20 15:41 UTC, merged