Update Automation Registry/Registrar addresses
smartcontractkit/documentation pull request #1647
Opened 2023-11-16 02:28 UTC by ritika-b

- updates Automation registry and registrar addresses

2023-11-16 22:20 UTC, thedriftofwords requested changes

2023-11-16 22:20 UTC, thedriftofwords commented on src/features/chainlink-automation/data/chainlink-automation-config.json
> +    "registrar": "0xaB9718E1DC7BD61Bd3440Fb771CC23DA0C0181a1",
Should this be the registrar address `0xA6deE996014d9670144943c2bc90755829398d07` as shown in your change to [chainlink-automation-addresses.json](https://github.com/smartcontractkit/documentation/pull/1647/files#diff-c5baa47f887aec758a3420ae29244422e1f111a0178aa9fc8b0ba2381ffcf5ff)?

2023-11-16 22:22 UTC, thedriftofwords commented on src/features/chainlink-automation/data/chainlink-automation-config.json
> +    "registrar": "0xaB9718E1DC7BD61Bd3440Fb771CC23DA0C0181a1",
```suggestion
    "registrar": "0xA6deE996014d9670144943c2bc90755829398d07",
```

2023-11-18 00:33 UTC, dwightjl approved these changes

2023-11-18 00:34 UTC, dwightjl commented on src/content/chainlink-automation/overview/getting-started.mdx
> +      2. Connect your cryptocurrency wallet to the app if you haven't done so already. You may also need to fetch Arbitrum Sepolia testnet LINK [here](https://faucets.chain.link/).
```suggestion
      2. Connect your cryptocurrency wallet to the app if you haven't done so already. You may also need to fetch Arbitrum Sepolia testnet LINK [here](https://automation.chain.link/arbitrum-sepolia).
```

2023-11-18 00:34 UTC, dwightjl commented on src/content/chainlink-automation/overview/getting-started.mdx
> +      2. Connect your cryptocurrency wallet to the app if you haven't done so already. You may also need to fetch Arbitrum Sepolia testnet LINK [here](https://faucets.chain.link/).
```suggestion
      2. Connect your cryptocurrency wallet to the app if you haven't done so already. You may also need to fetch Arbitrum Sepolia testnet LINK [here](https://automation.chain.link/arbitrum-sepolia).
```

2023-11-18 00:34 UTC, dwightjl commented on src/content/chainlink-automation/overview/getting-started.mdx
> +      2. Connect your cryptocurrency wallet to the app if you haven't done so already. You may also need to fetch Arbitrum Sepolia testnet LINK [here](https://faucets.chain.link/).
```suggestion
      2. Connect your cryptocurrency wallet to the app if you haven't done so already. You may also need to fetch Arbitrum Sepolia testnet LINK [here](https://automation.chain.link/arbitrum-sepolia).
```

2023-11-18 00:50 UTC, merged