QS: CCIP cross-chain NFT
smartcontractkit/documentation pull request #1693
Opened 2023-12-12 17:03 UTC by thedriftofwords

Add https://github.com/smartcontractkit/ccip-cross-chain-nft as a quickstart

2024-01-12 02:30 UTC, dwightjl requested changes

2024-01-12 02:30 UTC, dwightjl commented on src/content/quickstarts/ccip-cross-chain-nft.mdx
> +### Configure environment variables
These sections are showing up under the Before you begin section. Should this be part of its own independent section. I think we typically call this "Steps to implement".

Also, is this tutorial in a format that works with the collapsible sections like in the [Batch Reveal](https://docs.chain.link/quickstarts/batch-reveal) quickstart? Add the collapsible sections if possible, but it's not a requirement if they conflict with other elements on this page.

2024-01-19 19:59 UTC, Spunsd commented
Force it to

2024-01-19 20:07 UTC, Spunsd commented
Thanks!

2025-02-19 22:24 UTC, closed without merging