Minor edits to Data Streams docs
smartcontractkit/documentation pull request #1732
Opened 2024-01-22 16:30 UTC by khadni

2024-01-22 17:38 UTC, dwightjl requested changes

2024-01-22 17:38 UTC, dwightjl commented on src/content/data-streams/index.mdx
> +1. The `checkLog` function uses a `revert` with a custom error called `StreamsLookup`. This approach, aligning with [EIP-3668](https://eips.ethereum.org/EIPS/eip-3668#use-of-revert-to-convey-call-inf
```suggestion
1. The `checkLog` function uses a `revert` with a custom error called `StreamsLookup`. This approach aligns with [EIP-3668](https://eips.ethereum.org/EIPS/eip-3668#use-of-revert-to-convey-call-information) and conveys the required information through the data in the `revert` custom error.
```

Avoiding gerunds makes sentences easier to read and usually easier to translate.

2024-01-22 17:38 UTC, dwightjl commented on src/content/data-streams/release-notes.mdx
> +<Aside type="note" title="MAINNET EARLY ACCESS">
```suggestion
<Aside type="note" title="Mainnet Early Access">
```

Make this consistent even though callout titles are converted to all caps in the public docs. If the style changes in the future, it's easier to maintain.

2024-01-22 17:38 UTC, dwightjl commented on src/content/data-streams/reference/interfaces.mdx
> +<Aside type="note" title="MAINNET EARLY ACCESS">
```suggestion
<Aside type="note" title="Mainnet Early Access">
```

Make this consistent even though callout titles are converted to all caps in the public docs. If the style changes in the future, it's easier to maintain.

2024-01-22 17:38 UTC, dwightjl commented on src/features/data-streams/common/gettingStarted.mdx
> +This guide shows you how to read data from a Data Stream and validate and store the answer onchain. This example uses a [Chainlink Automation Log Trigger](/chainlink-automation/guides/log-trigger) to
```suggestion
This guide shows you how to read data from a Data Stream, validate the answer, and store the answer onchain. This example uses a [Chainlink Automation Log Trigger](/chainlink-automation/guides/log-trigger) to check for events that require data. For this example, the log trigger comes from a simple emitter contract. Chainlink Automation then uses `StreamsLookup` to retrieve a signed report from the Data Streams Engine, return the data in a callback, and run the [`performUpkeep` function](/chainlink-automation/reference/automation-interfaces#performupkeep-function-for-log-triggers) on your registered upkeep contract. The `performUpkeep` function calls the `verify` function on the verifier contract.
```

2024-01-22 17:38 UTC, dwightjl commented on src/features/data-streams/common/gettingStarted.mdx
> +This contract emits logs that trigger the upkeep. This code can be part of your dApp. For example, you might emit log triggers when your users initiate a trade or other action requiring data retrieva
```suggestion
This contract emits logs that trigger the upkeep. This code can be part of your dApp. For example, you might emit log triggers when your users initiate a trade or other action requiring data retrieval. For this Getting Started guide, use a very simple emitter so you can test the upkeep and data retrieval.
```

Avoid "we" and just use imperative sentences for simplicity.

2024-01-22 17:38 UTC, dwightjl commented on src/features/data-streams/common/gettingStarted.mdx
> +1. In Remix, under the **Deploy & Run Transactions** tab, ensure the **Environment** is still set to _Injected Provider - MetaMask_.
```suggestion
1. On the **Deploy & Run Transactions** tab in Remix, ensure the **Environment** is still set to _Injected Provider - MetaMask_.
```

This one is just a style choice, but I think it simplifies the sentence.

2024-01-22 17:38 UTC, dwightjl commented on src/features/data-streams/common/gettingStarted.mdx
> +After the transaction is complete, the log is emitted, and the upkeep is triggered. You can find the upkeep transaction hash at [Chainlink Automation UI](https://automation.chain.link/arbitrum-sepoli
```suggestion
After the transaction is complete, the log is emitted, and the upkeep is triggered. You can find the upkeep transaction hash in the [Chainlink Automation UI](https://automation.chain.link/arbitrum-sepolia). Check to make sure the transaction is successful.
```

2024-01-22 17:38 UTC, dwightjl commented on src/features/data-streams/common/gettingStarted.mdx
> +1. In Remix, under the **Deploy & Run Transactions** tab, expand your upkeep contract in the **Deployed Contracts** section.
```suggestion
1. On the **Deploy & Run Transactions** tab in Remix, expand the details of your upkeep contract in the **Deployed Contracts** section.
```

Style preference

2024-01-22 17:38 UTC, dwightjl commented on src/features/data-streams/common/gettingStarted.mdx
> +Alternatively, you can view the price emitted in the logs for your upkeep transaction. You can find the upkeep transaction hash at [Chainlink Automation UI](https://automation.chain.link/arbitrum-sep
```suggestion
Alternatively, you can view the price emitted in the logs for your upkeep transaction. You can find the upkeep transaction hash at [Chainlink Automation UI](https://automation.chain.link/arbitrum-sepolia) and view the transaction logs in the [Arbitrum Sepolia explorer](https://sepolia.arbiscan.io/).
```

2024-01-22 17:38 UTC, dwightjl commented on src/features/data-streams/common/gettingStarted.mdx
> +The code example uses `revert` with `StreamsLookup` to convey call information about what streams to retrieve. See the [eip-3668 rationale](https://eips.ethereum.org/EIPS/eip-3668#rationale) for more
```suggestion
The code example uses `revert` with `StreamsLookup` to convey call information about what streams to retrieve. See the [EIP-3668 rationale](https://eips.ethereum.org/EIPS/eip-3668#rationale) for more information about how to use `revert` in this way.
```

2024-01-22 20:31 UTC, dwightjl approved these changes

2024-01-23 08:49 UTC, Spunsd commented
Hello

2024-01-23 16:56 UTC, merged