CLA StreamsLookup ErrorHandler
smartcontractkit/documentation pull request #1795
Opened 2024-03-06 17:56 UTC by thedriftofwords

2024-03-06 22:48 UTC, dwightjl requested changes

2024-03-06 22:48 UTC, dwightjl commented on src/content/chainlink-automation/guides/streams-lookup-error-handler.mdx
> +- Specifying an incorrect feedID to force error code 800400 (`ErrCodeStreamsBadRequest`)
```suggestion
- Specifying an incorrect `feedID` to force error code 800400 (`ErrCodeStreamsBadRequest`)
```

2024-03-06 22:48 UTC, dwightjl commented on src/content/chainlink-automation/guides/streams-lookup-error-handler.mdx
> +- Specifying a future timestamp to force error code 808206 (where partial content is received) for both single feedID and bulk feedID requests
```suggestion
- Specifying a future timestamp to force error code 808206 (where partial content is received) for both single `feedID` and bulk `feedID` requests
```

2024-03-06 22:48 UTC, dwightjl commented on src/features/chainlink-automation/common/StreamsLookupInterface.mdx
> +This function is simulated offchain to respond to [error codes](/chainlink-automation/guides/streams-lookup-error-handler#error-codes) before sending data onchain via `performUpkeep`.
```suggestion
This function is simulated offchain to respond to [error codes](/chainlink-automation/guides/streams-lookup-error-handler#error-codes) before sending data onchain in the `performUpkeep` function. 
```

2024-03-06 22:48 UTC, dwightjl commented on src/features/chainlink-automation/common/StreamsLookupInterface.mdx
> +| `errorCode`      | `uint` | Error code returned by StreamsLookup error handler | e.g. "800400" (`ErrCodeStreamsBadRequest`) |
```suggestion
| `errorCode`      | `uint` | Error code returned by StreamsLookup error handler | Example: "800400" (`ErrCodeStreamsBadRequest`) |
```

2024-03-06 22:48 UTC, dwightjl commented on src/features/chainlink-automation/common/StreamsLookupInterface.mdx
> +| `extraData`   | `bytes`   | Bytes data sent as part of original MercuryLookup revert error | e.g. can send log data if you want to decode to use                            |
```suggestion
| `extraData`   | `bytes`   | Bytes data sent as part of the original `MercuryLookup` revert error | This field can send log data if you want to decode it and use it.                            |
```

2024-03-06 22:48 UTC, dwightjl commented on src/features/chainlink-automation/common/StreamsLookupInterface.mdx
> +| `upkeepNeeded` | `boolean` | When set to `true` this will trigger the `performUpkeep` function to be executed onchain                                                        | `true` of `false`  |
```suggestion
| `upkeepNeeded` | `boolean` | When set to `true`, this triggers the `performUpkeep` function to be executed onchain                                                        | `true` or `false`  |
```

2024-03-06 22:55 UTC, dwightjl approved these changes

2024-03-07 11:42 UTC, khadni requested changes

2024-03-07 11:42 UTC, khadni commented on src/content/chainlink-automation/guides/streams-lookup-error-handler.mdx
> +    bytes calldata errorCode,
Is `errorCode` of type `bytes calldata` or `uint`? In the snippet above, it is a `uint`.

2024-03-07 12:23 UTC, khadni requested changes

2024-03-07 12:23 UTC, khadni commented on src/content/chainlink-automation/guides/streams-lookup-error-handler.mdx
> +  bool upkeepNeeded = true;
```suggestion
  bool _upkeepNeeded = true;
```

2024-03-07 12:23 UTC, khadni commented on src/content/chainlink-automation/guides/streams-lookup-error-handler.mdx
> +    upkeepNeeded = false;
```suggestion
    _upkeepNeeded = false;
```

2024-03-07 12:23 UTC, khadni commented on src/content/chainlink-automation/guides/streams-lookup-error-handler.mdx
> +  return (upkeepNeeded, abi.encode(errorCode, extraData, success));
```suggestion
  return (_upkeepNeeded, abi.encode(errorCode, extraData, success));
```

2024-03-07 19:21 UTC, dwightjl approved these changes

2024-03-07 20:35 UTC, merged