Update PoR Wallet Address cross-chain reserves description
smartcontractkit/documentation pull request #1860
Opened 2024-04-01 21:36 UTC by dwightjl

2024-04-01 21:42 UTC, rui-zhang89 reviewed
Can we change the "attest" wording to "report" instead? 
- The project attests which addresses they own through a self-hosted API.
- Chainlink is not responsible for the accuracy of self-attested reserves data.

2024-04-02 16:08 UTC, aelmanaa submitted a review, later dismissed

2024-04-02 16:08 UTC, aelmanaa commented on src/content/data-feeds/proof-of-reserve/index.mdx
> +- Wallet address: The project reports which addresses they own through a self-hosted API. Reserve data reported by asset issuer's self-hosted API carries additional risks. Chainlink is not responsibl
```suggestion
- Wallet address: The project reports which addresses they own through a self-hosted API. Reserve data reported by asset issuer's self-hosted API carries additional risks. Chainlink Labs is not responsible for the accuracy of self-reported reserves data. Users must do their own risk assessment for asset issuer risk.
```

2024-04-02 20:42 UTC, rui-zhang89 requested changes

2024-04-02 20:42 UTC, rui-zhang89 commented on src/content/data-feeds/proof-of-reserve/index.mdx
> +- Wallet address manager: The project uses the [IPoRAddressList](https://github.com/smartcontractkit/chainlink/blob/master/contracts/src/v0.8/interfaces/PoRAddressList.sol) wallet address manager con
Append this disclaimer at the end of the sentence as well:

> Reserve data reported by an asset issuer's self-hosted API carries additional risks. Chainlink Labs is not responsible for the accuracy of self-reported reserves data. Users must do their own risk assessment for asset issuer risk.

2024-04-02 20:42 UTC, rui-zhang89 commented on src/content/data-feeds/proof-of-reserve/index.mdx
> +- ⚠️ Self-reported: Reserve data is read from an API that the token issuer hosts. Self-reported feeds carry additional risk.
Append this disclaimer at the end of the sentence as well:

> Reserve data reported by an asset issuer's self-hosted API carries additional risks. Chainlink Labs is not responsible for the accuracy of self-reported reserves data. Users must do their own risk assessment for asset issuer risk.

2024-04-02 20:42 UTC, rui-zhang89 commented on src/features/feeds/callouts/por-wallet-address-manager.mdx
> +Cross-chain Proof of Reserve feeds using wallet address manager contracts can vary in their configurations. If the wallet address manager is self-reporting, these feeds might include reserve balances
Append this disclaimer at the end of the sentence as well:

> Chainlink Labs is not responsible for the accuracy of self-reported reserves data. Users must do their own risk assessment for asset issuer risk.

2024-04-03 02:06 UTC, rui-zhang89 approved these changes

2024-04-04 16:49 UTC, merged