CLA on Amoy
smartcontractkit/documentation pull request #1903
Opened 2024-04-23 19:19 UTC by thedriftofwords

2024-04-23 21:05 UTC, friedemannf requested changes
Also, could we use `https://amoy.polygonscan.com/` as the explorer?

2024-04-23 21:05 UTC, friedemannf commented on src/features/chainlink-automation/data/chainlink-automation-config.json
> +    "checkGasLimit": 6500000,
```suggestion
    "checkGasLimit": 10000000,
```

2024-04-23 21:05 UTC, friedemannf commented on src/features/chainlink-automation/data/chainlink-automation-config.json
> +      "hex": "0x2e90edd000"
```suggestion
      "hex": "0xe8d4a51000"
```

2024-04-23 21:05 UTC, friedemannf commented on src/features/chainlink-automation/data/chainlink-automation-config.json
> +      "hex": "0x470de4df820000"
```suggestion
      "hex": "0x5c810d82e2bcd360"
```

2024-04-23 21:05 UTC, friedemannf commented on src/features/chainlink-automation/data/chainlink-automation-config.json
> +    "stalenessSeconds": 90000,
```suggestion
    "stalenessSeconds": 360000,
```

2024-04-23 21:05 UTC, friedemannf commented on src/features/chainlink-automation/data/chainlink-automation-config.json
> +    "transcoder": "0x0000000000000000000000000000000000000000"
```suggestion
    "transcoder": "0x703C1d261a996755409c74d00871e7D6Af4d9896"
```

2024-04-23 21:21 UTC, thedriftofwords commented
> Also, could we use `https://amoy.polygonscan.com/` as the explorer?

Yes I have that in #1904

2024-04-23 21:48 UTC, dwightjl approved these changes

2024-04-24 14:36 UTC, thedriftofwords commented
https://automation.chain.link/polygon-amoy is live

2024-04-24 14:36 UTC, merged