VRF subscription mock
smartcontractkit/documentation pull request #1946
Opened 2024-05-13 20:50 UTC by thedriftofwords

Copy of vrf-more branch from #1931 

- https://documentation-git-fork-thedriftofwords-vrf-09248c-chainlinklabs.vercel.app/vrf/v2-5/subscription/test-locally

2024-05-31 00:03 UTC, khadni requested changes

2024-05-31 00:03 UTC, khadni commented on public/samples/VRF/mock/VRFv2_5Consumer.sol
> +    address s_owner;
The consumer contract already inherits the storage variable `owner` from `ConfirmedOwnerWithProposal`, it is not necessary to redefine it.

2024-05-31 00:03 UTC, khadni commented on public/samples/VRF/mock/VRFv2_5Consumer.sol
> +        s_owner = msg.sender;
```suggestion

```

2024-05-31 00:03 UTC, khadni commented on public/samples/VRF/mock/VRFv2_5Consumer.sol
> +        s_owner = msg.sender;
same as above

2024-05-31 20:35 UTC, thedriftofwords commented on public/samples/VRF/mock/VRFv2_5Consumer.sol
> +pragma solidity ^0.8.19;
Yes, thanks! Updated in [b4c5cdd](https://github.com/smartcontractkit/documentation/pull/1946/commits/b4c5cdd98c1448d204f4521bb7b60610def9446d)

2024-06-01 00:18 UTC, dwightjl approved these changes
Minor edits

2024-06-01 00:18 UTC, dwightjl commented on src/content/vrf/v2-5/subscription/test-locally.mdx
> +1. Each time you make a VRF request, your consumer contract requests two random words. After the request is fulfilled, the two random words are stored in the `s_randomWords` array. You can check the
```suggestion
1. For each VRF request, your consumer contract requests two random words. After a request is fulfilled, the two random words are stored in the `s_randomWords` array. You can check the stored random words by reading the two first indexes of the `s_randomWords` array. To do so, click the _s_randomWords_ function and:
```

2024-06-01 00:18 UTC, dwightjl commented on src/content/vrf/v2-5/subscription/test-locally.mdx
> +This guide demonstrated how to test a VRF v2.5 consumer contract on your local blockchain. We made the guide on RemixIDE for learning purposes, but you can reuse the same [testing logic](#testing-log
```suggestion
This guide demonstrated how to test a VRF v2.5 consumer contract on your local blockchain. The guide uses the Remix IDE for learning purposes, but you can reuse the same [testing logic](#testing-logic) in another development environment, such as Hardhat. For example, see the Hardhat Starter Kit [RandomNumberConsumer unit tests](https://github.com/smartcontractkit/hardhat-starter-kit/blob/main/test/unit/RandomNumberConsumer.spec.js).
```

2024-06-01 00:18 UTC, dwightjl commented on src/content/vrf/v2-5/subscription/test-locally.mdx
> +1. Click on _transact_ to deploy the _VRFCoordinatorV2_5Mock_ contract.
```suggestion
1. Click _transact_ to deploy the _VRFCoordinatorV2_5Mock_ contract.
```

2024-06-01 00:18 UTC, dwightjl commented on src/content/vrf/v2-5/subscription/test-locally.mdx
> +1. Click on `createSubscription` to create a new subscription.
```suggestion
1. Click `createSubscription` to create a new subscription.
```

2024-06-01 00:18 UTC, dwightjl commented on src/content/vrf/v2-5/subscription/test-locally.mdx
> +1. Click on _transact_ to deploy the _RandomNumberConsumerV2_5_ contract.
```suggestion
1. Click _transact_ to deploy the _RandomNumberConsumerV2_5_ contract.
```

2024-06-01 00:18 UTC, dwightjl commented on src/content/vrf/v2-5/subscription/test-locally.mdx
> +1. Click on _addConsumer_ and fill in the `_subid` with your subscription ID and `_consumer` with your deployed consumer contract address.
```suggestion
1. Click _addConsumer_ and fill in the `_subid` with your subscription ID and `_consumer` with your deployed consumer contract address.
```

2024-06-01 00:18 UTC, dwightjl commented on src/content/vrf/v2-5/subscription/test-locally.mdx
> +   1. Fill in the index with _0_ then click on _call_ to read the first random word.
```suggestion
   1. Fill in the index with _0_ then click _call_ to read the first random word.
```

2024-06-01 00:18 UTC, dwightjl commented on src/content/vrf/v2-5/subscription/test-locally.mdx
> +   1. You can read the second random word in a similar way: fill in the index with _1_ then click on _call_ to display the second random word.
```suggestion
   1. You can read the second random word in a similar way: fill in the index with _1_ then click _call_ to display the second random word.
```

2024-06-01 18:24 UTC, merged