QS - Automated Portfolio Manager
smartcontractkit/documentation pull request #1977
Opened 2024-06-13 23:25 UTC by khadni

2024-07-19 17:08 UTC, dwightjl requested changes

2024-07-19 17:08 UTC, dwightjl commented on src/content/quickstarts/automated-portfolio-manager.mdx
> +- **MarketData token**: You need a valid token from MarketData to fetch the [GVZ index](https://www.forex.com/ie/news-and-analysis/gvz-index/) value. [Create a free account](https://dashboard.marketd
```suggestion
- **MarketData token**: You need a valid token from MarketData to fetch the [GVZ index](https://www.forex.com/ie/news-and-analysis/gvz-index/) value. [Create a free account](https://dashboard.marketdata.app/marketdata/signup) and generate a token. The token will be emailed to you.
```

2024-07-19 17:08 UTC, dwightjl commented on src/content/quickstarts/automated-portfolio-manager.mdx
> +   forge compile
I'm getting:

```
forge compile
-bash: forge: command not found
```

Add installing Foundry to the requirements?

2024-09-13 17:50 UTC, thedriftofwords requested changes

2024-09-13 17:50 UTC, thedriftofwords commented on src/content/quickstarts/automated-portfolio-manager.mdx
> +The Automated Portfolio Manager automatically rebalances an investment portfolio using real-time data from on-chain and off-chain sources. These contracts enable adjustments in asset allocations with
```suggestion
The Automated Portfolio Manager automatically rebalances an investment portfolio using real-time data from onchain and offchain sources. These contracts enable adjustments in asset allocations within a portfolio based on dynamic market conditions, sentiment scores, and volatility indicators such as the Gold Volatility Index (GVZ). This approach provides a modern way to manage digital assets.
```

2024-09-13 17:50 UTC, thedriftofwords commented on src/content/quickstarts/automated-portfolio-manager.mdx
> +The example contract supports dynamic asset management using tokens that adhere to the ERC20 standard. For this demonstration, Mimic Tokens representing gold (mXAU), Wrapped Bitcoin (mWBTC), and Ethe
```suggestion
The example contract supports dynamic asset management using tokens that adhere to the ERC20 standard. For this demonstration, Mimic Tokens representing gold (mXAU), Wrapped Bitcoin (mWBTC), and Ethereum (mETH) are used as the underlying assets. These tokens are automatically bought or sold to mirror changes in crypto market sentiment and gold volatility (GVZ) to ensure the portfolio adjusts to evolving market conditions. This functionality demonstrates how blockchain and Chainlink technologies can be used to create a dynamic investment strategy that adapts to global financial movements in real time.
```

2024-09-13 17:50 UTC, thedriftofwords commented on src/content/quickstarts/automated-portfolio-manager.mdx
> +The example contract supports dynamic asset management using tokens that adhere to the ERC20 standard. For this demonstration, Mimic Tokens representing gold (mXAU), Wrapped Bitcoin (mWBTC), and Ethe
"real-time" is an adjective

2024-09-13 17:50 UTC, thedriftofwords commented on src/content/quickstarts/automated-portfolio-manager.mdx
> +**Note**: In a real-world use case, you can integrate the portfolio rebalancing mechanism with any DeFi protocol, such as a swapping mechanism, investments in ERC-4626 vaults, etc.
```suggestion
**Note**: In a real-world use case, you can integrate the portfolio rebalancing mechanism with any DeFi protocol, such as a swapping mechanism or investments in ERC-4626 vaults. 
```

2024-09-13 17:50 UTC, thedriftofwords commented on src/content/quickstarts/automated-portfolio-manager.mdx
> +- **Chainlink Functions subscription**: A Chainlink Functions subscription is required for this guide. If you do not already have a subscription, you can create one using the [Chainlink Functions UI]
```suggestion
- **Chainlink Functions subscription**: A Chainlink Functions subscription is required for this guide. If you do not already have a subscription, you can create one using the [Chainlink Functions Subscription Manager](https://functions.chain.link/).
```

2024-09-13 17:50 UTC, thedriftofwords commented on src/content/quickstarts/automated-portfolio-manager.mdx
> +1. Install the front-end and back-end dependencies:
```suggestion
1. Install the frontend and backend dependencies:
```

2024-09-13 17:50 UTC, thedriftofwords commented on src/content/quickstarts/automated-portfolio-manager.mdx
> +1. Fund your Functions subscription with at least 5 testnet LINK ([Chainlink Functions UI](https://functions.chain.link/)).
```suggestion
1. Fund your Functions subscription with at least 5 testnet LINK using the [Chainlink Functions Subscription Manager](https://functions.chain.link/).
```

2024-09-13 17:50 UTC, thedriftofwords commented on src/content/quickstarts/automated-portfolio-manager.mdx
> +1. Add your `OffChainDataFetcher` contract as a consumer in your Functions subscription ([Chainlink Functions UI](https://functions.chain.link/)). **Note**: You can find your deployed `OffchainDataFe
```suggestion
1. Add your `OffChainDataFetcher` contract as a consumer in your Functions subscription ([Chainlink Functions Subscription Manager](https://functions.chain.link/)). **Note**: You can find your deployed `OffchainDataFetcher` contract address in `output/deployedOffchainDataFetcher.json`.
```

2024-09-13 17:50 UTC, thedriftofwords commented on src/content/quickstarts/automated-portfolio-manager.mdx
> +   - Go to the [Chainlink Automation UI](https://automation.chain.link/).
```suggestion
   - Go to the [Chainlink Automation App](https://automation.chain.link/).
```

2024-09-13 17:50 UTC, thedriftofwords commented on src/content/quickstarts/automated-portfolio-manager.mdx
> +   - Create a Time-based upkeep that targets the `sendRequestCBOR` function.
```suggestion
   - Create a time-based upkeep that targets the `sendRequestCBOR` function.
```

2024-09-13 17:50 UTC, thedriftofwords commented on src/content/quickstarts/automated-portfolio-manager.mdx
> +   - Call the `setAutomationCronContract` function with the `Upkeep address` as the input parameter. **Note**: You can find the `Upkeep address` in the Details section of your upkeep in the [Automati
```suggestion
   - Call the `setAutomationCronContract` function with the `Upkeep address` as the input parameter. **Note**: You can find the `Upkeep address` in the Details section of your upkeep in the [Chainlink Automation App](https://automation.chain.link/).
```

2024-09-13 17:50 UTC, thedriftofwords commented on src/content/quickstarts/automated-portfolio-manager.mdx
> +1. Go to the [Chainlink Automation UI](https://automation.chain.link/).
```suggestion
1. Go to the [Chainlink Automation App](https://automation.chain.link/).
```

2024-09-13 17:50 UTC, thedriftofwords commented on src/content/quickstarts/automated-portfolio-manager.mdx
> +   - In the function inputs, enter the `Forwarder address` into the `setAutomationUpkeepForwarderContract` function. **Note**: You can find the `Forwarder address` in the Details section of your upke
```suggestion
   - In the function inputs, enter the `Forwarder address` into the `setAutomationUpkeepForwarderContract` function. **Note**: You can find the `Forwarder address` in the Details section of your upkeep in the [Automation App](https://automation.chain.link/).
```

2024-09-13 18:54 UTC, thedriftofwords approved these changes

2024-09-18 18:53 UTC, merged