Update DataConsumerWithSequencerCheck.sol
smartcontractkit/documentation pull request #1995
Opened 2024-07-08 18:25 UTC by aviggiano

**IMPORTANT: Please do not create a Pull Request without creating an issue first.Any change needs to be discussed before proceeding.**

## Closing issues

Closes https://github.com/smartcontractkit/documentation/issues/1994

## Description

Updates code sample to match documentation

## Changes

- After a recent security review, an auditor pointed out that the L2 Sequencer Feed code sample does not match the recommendation from the docs
- This PR fixes the code sample to match the documentation
- See https://github.com/code-423n4/2024-06-size-findings/issues/209

2024-07-13 17:59 UTC, dwightjl commented
Thank you for opening this PR. I'm confirming how best to handle situations where `startedAt==0`. I'm not sure if an invalid round should cause `isSequencerUp` to be `false`.

2024-07-19 12:49 UTC, dwightjl commented
My understanding is that correctly handling `startedAt == 0` is application-dependent, but it is good to highlight that it is available. I'll get a review on this change.

2024-07-29 11:58 UTC, thedriftofwords requested changes

2024-07-29 11:58 UTC, thedriftofwords commented on src/content/data-feeds/l2-sequencer-feeds.mdx
>  - `answer`: A variable with a value of either `1` or `0`
```suggestion
- `answer`: A variable with a value of either `0` or `1`
```

2024-07-29 11:58 UTC, thedriftofwords commented on public/samples/DataFeeds/DataConsumerWithSequencerCheck.sol
> +    // error InvalidUptimeFeedRound();
Are we keeping this commented out line for any particular reason?

2024-08-01 17:44 UTC, dwightjl commented
Still getting confirmation on some changes here.

2024-08-08 15:24 UTC, dwightjl approved these changes

2024-08-08 15:25 UTC, merged