Cleanup and simplify Fulfilling Requests page.
smartcontractkit/documentation pull request #208
Opened 2021-07-09 03:58 UTC by dwightjl

View staged changes here: https://home.taters.org/docs/fulfilling-requests/

Changes for fulfilling-requests.md:
- Convert image blocks and headers to MD.
- Convert some callouts to MD, but keep critical callouts in old format. (Is there MD for the bright red callouts?)
- Add alt text to images for accessibility.
- Clean up the requirements section to provide a full list of requirements rather that one requirement with many sub-requirements and one callout box.
- Remove ./files/f8ffdc0-c6925db-remix007.jpg which is outdated and no longer necessary.

2021-07-12 10:24 UTC, alexroan requested changes

2021-07-12 10:24 UTC, alexroan commented on docs/Node Operators/fulfilling-requests.md
> +##Requirements
This renders fine, but could we add a space in between the hashes and the text for conformity with the rest of the page, please?

```suggestion
## Requirements
```

2021-07-12 10:24 UTC, alexroan commented on docs/Node Operators/fulfilling-requests.md
> +##Deploy your own Oracle contract
```suggestion
## Deploy your own Oracle contract
```

2021-07-12 10:24 UTC, alexroan commented on docs/Node Operators/fulfilling-requests.md
> +##Create a request to your node
```suggestion
## Create a request to your node
```

2021-07-22 00:04 UTC, dwightjl commented
Re-synced and ready to merge. All suggested changes are integrated.

2021-08-14 00:02 UTC, dwightjl commented
Updated and merged. See the PR description for the current list of changes.

2021-08-19 15:40 UTC, PatrickAlphaC requested changes
Great! Just one comment.

2021-08-23 22:13 UTC, dwightjl commented on docs/Node Operators/fulfilling-requests.md
> +- [Run an Ethereum Client](../run-an-ethereum-client/) that your Chainlink Node can access.
Good feedback. I clarified the difference and linked to the external services section of the ../run-an-ethereum-client/ doc.

2021-09-03 19:48 UTC, dwightjl commented
@PatrickAlphaC  @alexroan  This is ready to merge. Can you review it once more?

2021-09-09 14:06 UTC, PatrickAlphaC approved these changes

2021-09-09 16:47 UTC, merged