add heco to the list of supported chains
smartcontractkit/documentation pull request #252
Opened 2021-07-22 05:22 UTC by dmitrydao

fixes #238

2021-07-22 13:10 UTC, StephenFluin requested changes
Why is the address empty / `?`?

2021-07-27 10:06 UTC, dmitrydao commented
> Why is the address empty / `?`?

Because I don't know the address and I'm waiting for access to the repo that will give me the answers for this.
That's why it's WIP

2021-07-27 12:11 UTC, StephenFluin commented
I missed that this was a draft. Perfect! Sorry!

2021-07-29 19:38 UTC, StephenFluin approved these changes

2021-07-29 19:41 UTC, merged