Fully update config var documentation
smartcontractkit/documentation pull request #260
Opened 2021-07-23 12:15 UTC by PiotrTrzpil

2021-07-23 15:14 UTC, PiotrTrzpil commented on docs/Node Operators/configuration-variables.md
> -  - [ETH_GAS_LIMIT_TRANSFER](#eth_gas_limit_transfer)
these were duplicates

2021-07-27 16:11 UTC, StephenFluin requested changes
This looks great! Can you squash and rebase the PR and we'll be able to merge it.

2021-08-03 09:36 UTC, PiotrTrzpil commented
@StephenFluin I always squash when merging, via github button. I'll edit the commit description as well then

2021-08-10 13:10 UTC, StephenFluin approved these changes

2021-08-10 13:23 UTC, merged