added multi-variable and large responses links back in
smartcontractkit/documentation pull request #283
Opened 2021-08-06 12:30 UTC by PatrickAlphaC

2021-08-14 04:02 UTC, StephenFluin commented
@dwightjl need to figure out how it got removed and see where the process is failing if it is

2021-08-14 04:04 UTC, StephenFluin requested changes
Remove the extra commas and we're good to go

2021-08-14 04:04 UTC, StephenFluin commented on _data/navigation.js
> +          ,
I think this comma is extra

2021-08-14 04:04 UTC, StephenFluin commented on _data/navigation.js
> +          ,
This one should be removed too

2021-08-14 04:28 UTC, dwightjl commented
> @dwightjl need to figure out how it got removed and see where the process is failing if it is

Looks like the changes to navigation.js got clobbered in 23ec285 right before PR #270 merged.    https://github.com/smartcontractkit/documentation/commit/23ec285b36b23db8ed8822e643f229df264fbb99

I've made that mistake before.

2021-08-17 11:50 UTC, dmitrydao commented
replaced with #302, which is already approved

2021-08-17 11:50 UTC, closed without merging

2021-08-17 14:35 UTC, dwightjl commented
@dmitrydao Closing this PR is ok, but in the future let's keep duplicate PRs open until one of them is merged. Approval from me is not the same as merging or closing the PR.