Update references to faucets in the docs
smartcontractkit/documentation pull request #328
Opened 2021-08-24 18:25 UTC by bradford-m

2021-08-25 09:53 UTC, ainsleybc requested changes
Maybe check with the docs owners before making any of my suggested changes..

2021-08-25 09:53 UTC, ainsleybc commented on docs/Developer Reference/link-token-contracts.md
> +> Testnet LINK is available from <a href="https://faucets.chain.link/chapel" target="_blank" rel="noreferrer, noopener">the community faucet</a>.
I don't think these are community faucets any more - maybe the text should match what we say above for kovan/rinkeby?

2021-08-25 09:53 UTC, ainsleybc commented on docs/Developer Reference/link-token-contracts.md
> +> Testnet LINK and MATIC are available from <a href="https://faucet.matic.network/" target="_blank" rel="noreferrer, noopener">the official matic faucet</a> and <a href="https://faucets.chain.link/mu
same here

2021-08-25 09:53 UTC, ainsleybc commented on docs/Developer Reference/link-token-contracts.md
> +> Community Faucet: https://faucets.chain.link/fuji
same here

2021-08-25 09:53 UTC, ainsleybc commented on docs/Developer Reference/link-token-contracts.md
> +> Community Faucet: https://faucets.chain.link//fantomtestnet
same here

2021-08-25 09:53 UTC, ainsleybc commented on docs/Developer Reference/link-token-contracts.md
> +> Community Faucet: https://faucets.chain.link/arb-rinkeby
same here

2021-08-25 09:53 UTC, ainsleybc commented on docs/Developer Reference/user-guides/acquire-link.md
> +> You can also get testnet LINK from: [Rinkeby](https://faucets.chain.link/rinkeby)
Kind of feel like this shouldn't be here, or we should give the full list of networks you can use

2021-08-25 09:53 UTC, ainsleybc commented on docs/Using Randomness/vrf-contracts.md
> +> Testnet LINK and MATIC are available from <a href="https://faucet.matic.network/" target="_blank" rel="noreferrer, noopener">the official matic faucet</a> and <a href="https://faucets.chain.link/mu
same here

2021-08-25 09:53 UTC, ainsleybc commented on docs/Using Randomness/vrf-contracts.md
> +> Testnet LINK is available from <a href="https://faucets.chain.link/bsctest" target="_blank" rel="noreferrer, noopener">the community faucet</a>.
last one

2021-09-09 15:08 UTC, dwightjl requested changes

2021-09-09 15:08 UTC, dwightjl commented on docs/Developer Reference/link-token-contracts.md
> +> Testnet LINK/ETH is available from https://faucets.chain.link/kovan
```suggestion
> Testnet LINK and ETH are available from https://faucets.chain.link/kovan
```

2021-09-09 15:08 UTC, dwightjl commented on docs/Using Randomness/vrf-contracts.md
> +> Testnet LINK/ETH is available from https://faucets.chain.link/kovan
```suggestion
> Testnet LINK and ETH are available from https://faucets.chain.link/kovan
```

2021-09-09 15:08 UTC, dwightjl commented on _includes/samples/DataProviders/AlarmClock.sol
> + *     - Kovan LINK/ETH faucet: https://faucets.chain.link/kovan
```suggestion
 *     - Kovan LINK and ETH faucet: https://faucets.chain.link/kovan
```

2021-09-09 15:26 UTC, dwightjl approved these changes

2021-09-09 15:48 UTC, PatrickAlphaC approved these changes

2021-09-09 16:01 UTC, dwightjl commented
I tested the preview links and confirmed with Bradford that this is ready to merge.

2021-09-09 16:01 UTC, merged