updated for new getting help process
smartcontractkit/documentation pull request #396
Opened 2021-09-28 02:44 UTC by PatrickAlphaC

2021-09-28 02:45 UTC, PatrickAlphaC commented
@dwightjl to get Stackoverflow and stack exchange ETH links in our footer, would we have to chat with julian and the design team?

2021-09-28 04:39 UTC, dwightjl requested changes

2021-09-28 04:39 UTC, dwightjl commented on docs/Developer Reference/getting-help.md
> +If you run into issues and the available documentation, videos, and code repositories are not able to assist you, the best way to get help is to follow this support escalation process. Start with ste
```suggestion
If you run into issues and the available documentation, videos, and code repositories are not able to assist you, the best way to get help is to follow the support escalation process in this document. Sometimes you might have a question that is too theoretical or hasn't been solved, so you might not always get what you're looking for!
```

2021-09-28 04:39 UTC, dwightjl commented on docs/Developer Reference/getting-help.md
> +Often times, someone else has asked the question that you're asking. If you copy paste the error into the google or web search bar, there is a good chance that some helpful material will come up.
```suggestion
Often someone else has asked the same question that you're asking. If you copy and paste the error into the Google or web search bar, there is a good chance that you will find some helpful material from someone else who has already found the solution to your question.
```

2021-09-28 04:39 UTC, dwightjl commented on docs/Developer Reference/getting-help.md
> +## 3. Make an issue on the github or code repository
```suggestion
## 3. Open an issue on the github or code repository
```

2021-09-28 04:39 UTC, dwightjl commented on docs/Developer Reference/getting-help.md
> +This is only applicable if you're working with a certain set of code. For example, if you're having an issue working with the [Chainlink Hardhat Starter kit](https://github.com/smartcontractkit/hardh
```suggestion
This is only applicable if you're working with a certain set of code. For example, if you're having an issue working with the [Chainlink Hardhat Starter kit](https://github.com/smartcontractkit/hardhat-starter-kit), open an issue on the repo explaining exactly what's going on and someone might have the answer that you need.
```

2021-09-28 04:39 UTC, dwightjl commented on docs/Developer Reference/getting-help.md
> +- Remain clear and concise
```suggestion
- Be clear and concise about the issue that you are encountering
```

2021-09-28 04:39 UTC, dwightjl commented on docs/Developer Reference/getting-help.md
> +- Format your message ([using 3 backticks](https://discuss.codecademy.com/t/using-backticks-to-format-your-code/3697) will help format your code)
```suggestion
- Format your issue description. Use [three backticks (```)](https://discuss.codecademy.com/t/using-backticks-to-format-your-code/3697) to format format your code or log output.
```

2021-09-28 04:39 UTC, dwightjl commented on docs/Developer Reference/getting-help.md
> +- Please don't use screenshots, those *generally* make it harder!
```suggestion
- Don't use screenshots. Screenshots are not searchable and generally make it harder to understand your issue.
```

2021-09-28 04:39 UTC, dwightjl commented on docs/Developer Reference/getting-help.md
> +This is where the majority of people will end up, and is one of the most helpful resources out there. Stack Overflow is meant to be living documentation, so please do your best to make a [thoughtful,
```suggestion
This is where most people will end up and is one of the most helpful resources out there. Stack Overflow is living documentation, so do your best to make a [thoughtful and easy to triage question](https://stackoverflow.com/help/how-to-ask). This will make it much easier for people to help debug your issue and ensure it doesn't get removed from the site. Remember, we want to make this question **searchable** so others who run into the same issue can also get their question solved. You could use any forum-based site you like if you prefer another site over Stack Overflow. 
```

2021-09-28 04:39 UTC, dwightjl commented on docs/Developer Reference/getting-help.md
> +Here is an example of a not-so-well-formatted question:
```suggestion
Here is an example of a poorly formatted question:
```

2021-09-28 04:39 UTC, dwightjl commented on docs/Developer Reference/getting-help.md
> +Here is that same question, formatted much better:
```suggestion
Here is that same question with better formatting:
```

2021-09-28 04:39 UTC, dwightjl commented on docs/Developer Reference/getting-help.md
> +It's often recommended to come up with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help others understand your issue. This way, they can help you
```suggestion
It's best to create a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help others understand your issue. This way, they can help you get an answer quickly. Remember, its a community run platform!
```

2021-09-28 04:39 UTC, dwightjl commented on docs/Developer Reference/getting-help.md
> +Don't get discouraged if your question gets downvoted or removed, this just means you need to format your question a little differently next time!
```suggestion
Don't get discouraged if your question gets downvoted or removed. This just means you need to format your question a little differently next time!
```

2021-09-28 04:39 UTC, dwightjl commented on docs/Developer Reference/getting-help.md
> +And lastly, you can always just in the [discord](https://discord.gg/2YHSAey) and see if there is a community member who might be able to help you out. One of the best ways to ask the community, is to
```suggestion
And lastly, you can always ask the question in the [discord](https://discord.gg/2YHSAey) and see if there is a community member who might be able to help you out. One of the best ways to ask the community is to drop a link to your Stack Overflow question, issue, or the forum where you're asking a Chainlink question. Remember, these are community members, and they are helping because they are wonderful and kind individuals!
```

2021-09-28 04:39 UTC, dwightjl commented on docs/Developer Reference/hackathon-resources.md
> +ALWAYS refer back to the [getting help](/docs/getting-help) for how to get support.
```suggestion
Always refer back to the [getting help](/docs/getting-help) page for how to get support. 
```

2021-09-30 18:21 UTC, PatrickAlphaC commented
Updated @dwightjl

2021-10-01 05:21 UTC, dwightjl commented
I'll take a look Friday morning. Thanks for the updates!

2021-10-01 16:35 UTC, dwightjl requested changes

2021-10-01 16:35 UTC, dwightjl commented on docs/chainlink-keepers/faqs.md
> +We are here to help! For help with your use case, please [reach out directly](mailto:keeper@chain.link) and we would be happy to connect you with one of our Solutions Architects. You can also ask que
```suggestion
We are here to help! For help with your use case, please [reach out directly](mailto:keeper@chain.link) and we would be happy to connect you with one of our Solutions Architects. You can also ask questions about Chainlink Keepers on [Stack Overflow](https://stackoverflow.com/questions/ask?tags=chainlink) or in the [#keepers channel](https://discord.com/channels/592041321326182401/821350860302581771) in our [Discord server](https://discord.gg/qj9qarT).
```

2021-10-01 16:35 UTC, dwightjl commented on docs/Developer Reference/hackathon-resources.md
> +Always refer back to the [getting help](/docs/getting-help) page for how to get support.
```suggestion
Always refer back to the [getting help](/docs/getting-help) page for the latest information about how to get support. 
```

2021-10-01 16:35 UTC, dwightjl commented on docs/Developer Reference/getting-help.md
> +## 2. Do a web search for the specific error or situation you're in.
```suggestion
## 2. Do a web search for the specific error or situation you're in
```

2021-10-01 16:35 UTC, dwightjl commented on docs/Developer Reference/getting-help.md
> +### Where do I go to get help and support?
```suggestion
## Where do I go to get help and support? 
```

2021-10-01 17:10 UTC, dwightjl approved these changes

2021-10-01 17:17 UTC, dwightjl requested changes
One more change.

2021-10-01 17:17 UTC, dwightjl commented on docs/Developer Reference/getting-help.md
> +- Format your issue description. Use [three backticks (```)](https://discuss.codecademy.com/t/using-backticks-to-format-your-code/3697) to format format your code or log output.
```suggestion
- Format your issue description. Use [three backticks (```)](https://www.freecodecamp.org/news/how-to-format-code-in-markdown/#code-blocks) to format format your code or log output.
```

2021-10-01 17:26 UTC, dwightjl requested changes

2021-10-01 17:26 UTC, dwightjl commented on docs/Developer Reference/getting-help.md
> +And lastly, you can always ask the question in the [discord](https://discord.gg/2YHSAey) and see if there is a community member who might be able to help you out. One of the best ways to ask the comm
```suggestion
And lastly, you can always ask the question in the [Discord](https://discord.gg/2YHSAey) and see if there is a community member who might be able to help you out. One of the best ways to ask the community is to drop a link to your Stack Overflow question, issue, or the forum where you're asking a Chainlink question. Remember, these are community members, and they are helping because they are wonderful and kind individuals!
```

2021-10-01 17:26 UTC, dwightjl commented on docs/Developer Reference/getting-help.md
> +It's best to create a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help others understand your issue. This way, they can help you get an answer quick
```suggestion
It's best to create a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help others understand your issue. This way, they can help you get an answer quickly. Remember, its a community-run platform!
```

2021-10-01 17:26 UTC, dwightjl commented on docs/Developer Reference/getting-help.md
> +## 3. Open an issue on the github or code repository
```suggestion
## 3. Open an issue on GitHub or the code repository
```

2021-10-04 16:21 UTC, dwightjl approved these changes

2021-10-04 16:27 UTC, merged