change search events from keydown to keyup
smartcontractkit/documentation pull request #43
Opened 2021-04-28 16:00 UTC by StephenFluin

Fixes a bug where the last character you type isn't used for searching.

2021-04-28 21:54 UTC, alexroan requested changes

2021-04-28 21:54 UTC, alexroan commented on _includes/_search.html
> +        // console.log('timeout is activating!');
Better to remove these lines than comment out.

2021-04-28 21:54 UTC, alexroan commented on _includes/_search.html
> +      // console.log(searchTimeout);
Better to remove these lines than comment out.

2021-04-28 21:54 UTC, alexroan commented on _includes/_search.html
> +      console.log('perform search event',event,document.getElementById('search-query').value);
Is this needed?

2021-04-29 14:03 UTC, StephenFluin commented
@alexroan great call, dead code removed.

2021-04-29 14:26 UTC, alexroan approved these changes

2021-04-29 14:28 UTC, merged