updated adding EA to node to show TOML format
smartcontractkit/documentation pull request #450
Opened 2021-10-26 06:52 UTC by pappas999

- Updated old JSON format of jobs using EAs to be new TOML format
- Other various changes to terms that have changed from JSON to TOML jobs
- Small grammatical changes
- Updated screenshots
- Removed section on 'excluding parameters' as I don't believe it applies with TOML

2021-11-01 07:37 UTC, dwightjl requested changes
Just a few more changes and this is ready to merge.
Remember to batch suggested edits together.

2021-11-01 07:37 UTC, dwightjl commented on docs/External Adapters/node-operators.md
> +The easiest way is to setup a [Webhook Job](https://docs.chain.link/docs/jobs/types/webhook/) that uses the external adapter, and manually set the parameter.
```suggestion
The easiest way is to setup a [Webhook Job](/docs/jobs/types/webhook/) that uses the external adapter, and manually set the parameter.
```

2021-11-01 07:37 UTC, dwightjl commented on docs/External Adapters/node-operators.md
> +> Note: You may need to set the [configuration variable](https://docs.chain.link/docs/configuration-variables/) `FEATURE_WEBHOOK_V2=true` in your `.env` file.
```suggestion
> Note: You might need to set the [configuration variable](/docs/configuration-variables/) `FEATURE_WEBHOOK_V2=true` in your `.env` file.
```

2021-11-01 07:37 UTC, dwightjl commented on docs/External Adapters/node-operators.md
> +To add jobs that use the bridge, add a [Bridge Task](/docs/jobs/task-types/bridge/) to your job. The `bridge` task defined in the example below is defined as 'fetch' and the name of the bridge is `so
```suggestion
To add jobs that use the bridge, add a [Bridge Task](/docs/jobs/task-types/bridge/) to your job. The `bridge` task defined in the example below is defined as `fetch` and the name of the bridge is `soccer-data`.
```

2021-11-01 07:37 UTC, dwightjl commented on docs/External Adapters/node-operators.md
> +Let's say you have an external adapter called `soccer-data` and it's registered in the `bridges` section. It takes 1 parameter: `playerId`, and in solidity, you'd pass the parameter with:
```suggestion
As an example, assume you have an external adapter named `soccer-data` that is registered in the `bridges` section and it takes one parameter named `playerId`. In solidity, you would pass the parameter with the following request:
```

2021-11-01 07:37 UTC, dwightjl commented on docs/External Adapters/node-operators.md
> +```javascript
```suggestion
```solidity
```

2021-11-01 07:37 UTC, dwightjl commented on docs/External Adapters/node-operators.md
> +```toml
```suggestion
```jpv2
```
We're using custom highlighting for TOML and DOT now. See [https://github.com/smartcontractkit/documentation/commit/6b9e99d0d8092f49ab130536ecbfe9e267da27af](commit 6b9e99d0)

2021-11-01 07:37 UTC, dwightjl commented on docs/External Adapters/node-operators.md
> +```toml
```suggestion
```jpv2
```

2021-11-01 07:37 UTC, dwightjl commented on docs/External Adapters/node-operators.md
> +Adding the following into the TOML spec manually sets the parameters passed into the bridge task, and is equivalent to using `request.add` as shown above, or adding the data with the `--d` flag if yo
```suggestion
Adding the following into the TOML spec manually sets the parameters passed into the bridge task. It is equivalent to using `request.add` as shown above or adding the data with the `--d` flag if you're using [curl](https://curl.se/).
```

2021-11-03 01:07 UTC, pappas999 commented
thanks @dwightjl , suggested changes all LGTM

2021-11-03 06:28 UTC, dwightjl approved these changes

2021-11-03 06:51 UTC, merged