removed alpha chain oracle for devrel node, with ap election data
smartcontractkit/documentation pull request #456
Opened 2021-10-29 03:31 UTC by PatrickAlphaC

Fixes: https://github.com/smartcontractkit/documentation/issues/447

2021-10-30 15:42 UTC, dwightjl requested changes

2021-10-30 15:42 UTC, dwightjl commented on docs/Using Any API/existing-job-request.md
> +> The job spec for the Chainlink node in this example can be [found here](https://github.com/smartcontractkit/documentation/_includes/samples/APIRequests/ap-election-job.md).
```suggestion
You can find the job spec for this example on [GitHub](https://github.com/smartcontractkit/documentation/tree/main/_includes/samples/APIRequests/ap-election-job.toml).
```

2021-11-08 17:54 UTC, dwightjl commented
This seems to work: https://kovan.etherscan.io/tx/0x59abeb9c7531c5214e1ed147b1de7a4dbf4fa7819a2584e9ce4e0f958ce74554#eventlog

However Remix isn't displaying any results after I run `requestElectionWinner()`. Only `0x0000...` values. I don't have an API key so I can't check the AP Elections API directly.

2021-11-08 23:26 UTC, PatrickAlphaC commented
You shouldn't need to use an API key... The job I gave has the data defined on the Chainlink node itself. So you should just be able to run `APElection.sol ` and be good. Are you using an AP URL yourself?

2021-11-12 15:46 UTC, dwightjl requested changes

2021-11-12 15:46 UTC, dwightjl commented on _includes/samples/APIRequests/APElection.sol
> +        request.add("resultsType", "t"); // Replace with l for live results.
```suggestion
        request.add("resultsType", "l"); // Replace with l for live results.  
```
Change to live results.

2021-11-12 15:47 UTC, dwightjl approved these changes

2021-11-12 17:21 UTC, merged