Updated Registration Completion section
smartcontractkit/documentation pull request #545
Opened 2021-12-10 23:14 UTC by AnushV

Ordering update, some simplification and adding note on block confirmation time.

2021-12-11 17:33 UTC, dwightjl requested changes

2021-12-11 17:33 UTC, dwightjl commented on docs/chainlink-keepers/register-upkeep.md
> +
```suggestion
After you complete registration, your upkeep will start being serviced after a predefined block confirmation time, which is less than 10 minutes. The number of block confirmations might differ depending on which blockchain you selected.
```

2022-02-07 20:21 UTC, ritika-b approved these changes

2022-02-09 04:08 UTC, dwightjl approved these changes

2022-02-09 04:13 UTC, dwightjl commented
Rebased to main

2022-02-09 04:24 UTC, merged