Rebrand xDai to Gnosis Chain
smartcontractkit/documentation pull request #587
Opened 2022-01-17 19:06 UTC by dwightjl

2022-01-17 20:49 UTC, StephenFluin requested changes

2022-01-17 20:49 UTC, StephenFluin commented on docs/Using Price Feeds/xdai-price-feeds.md
> +title: "Gnosis Chain Data Feeds"
add "(formerly xDai)"

2022-01-21 17:51 UTC, dwightjl commented on docs/Using Price Feeds/xdai-price-feeds.md
> +title: "Gnosis Chain Data Feeds"
Added `(xDai)`.

2022-01-24 21:00 UTC, StephenFluin approved these changes

2022-01-25 00:14 UTC, merged