Add data provider nodes list
smartcontractkit/documentation pull request #64
Opened 2021-05-04 07:46 UTC by dmitrydao

fixes #63

2021-05-04 13:56 UTC, alexroan requested changes

2021-05-04 13:56 UTC, alexroan commented on docs/Data Provider Nodes/data-provider-nodes-list.md
> +|:------------------------------------------------------------------------- |:-------------------------------------------- |
Kraken Rates is missing

2021-05-04 14:15 UTC, dmitrydao commented on docs/Data Provider Nodes/data-provider-nodes-list.md
> +|:------------------------------------------------------------------------- |:-------------------------------------------- |
ooops, will add

2021-05-05 11:02 UTC, alexroan approved these changes

2021-05-05 11:03 UTC, merged