Add DappTools and Foundry starter kits
smartcontractkit/documentation pull request #656
Opened 2022-03-14 19:50 UTC by aelmanaa

fixes https://github.com/smartcontractkit/documentation/issues/654

2022-03-18 02:51 UTC, ritika-b requested changes

2022-03-21 02:38 UTC, dwightjl commented on docs/Developer Reference/create-a-chainlinked-project.md
> +For more details on how to use Chainlink with DappTools, see our blog post [How To Use DappTools](https://blog.chain.link/how-to-use-dapptools/).
```suggestion
## DappTools Starter Kit

To learn more about DappTools, refer to the [DappTools Documentation](https://dapp.tools/).

1. Install Dapp tools using the [Installation instructions](https://github.com/dapphub/dapptools#installation) in the Dapp tools GitHub repository.

1. After you install the tools, clone the starter kit and install the dependencies:

      ```shell
      git clone https://github.com/smartcontractkit/dapptools-starter-kit
      cd dapptools-starter-kit
      make # This installs the project's dependencies.
      ```

For instructions on how to use the starter kit, refer to the DappTools starter kit [README](https://github.com/smartcontractkit/dapptools-starter-kit#readme).

For more details on how to use Chainlink with DappTools, see our blog post [How To Use DappTools](https://blog.chain.link/how-to-use-dapptools/).
```

2022-03-21 02:38 UTC, dwightjl commented on docs/Developer Reference/create-a-chainlinked-project.md
> +For instructions on how to use the starter kit, refer to the [Foundry starter kit README](https://github.com/smartcontractkit/foundry-starter-kit#readme).
```suggestion
To learn more about Foundry, refer to the [Foundry Documentation](https://onbjerg.github.io/foundry-book/).

1. Install Foundry using the [Installation instructions](https://onbjerg.github.io/foundry-book/getting-started/installation.html) on GitHub.io.

1. After you install Foundry, clone the starter kit and install the projects dependencies:

      ```shell
      git clone https://github.com/smartcontractkit/foundry-starter-kit
      cd foundry-starter-kit
      make # This installs the project's dependencies.
      ```

For instructions on how to use the starter kit, refer to the [Foundry starter kit README](https://github.com/smartcontractkit/foundry-starter-kit#readme).
```

2022-03-21 02:48 UTC, dwightjl commented on docs/Developer Reference/create-a-chainlinked-project.md
> +1. After you install Foundry, clone the starter kit and install the projects dependencies:
```suggestion
1. After you install Foundry, clone the starter kit and install the project dependencies:
```

2022-03-21 02:53 UTC, dwightjl reviewed
Minor sentence edits

2022-03-21 02:53 UTC, dwightjl commented on docs/Developer Reference/create-a-chainlinked-project.md
> +For more details on how to use Chainlink with Hardhat, see our blog post [How to use Hardhat with Chainlink](https://blog.chain.link/using-chainlink-with-hardhat/).
```suggestion
For more details on how to use Chainlink with Hardhat, see our blog post about [How to use Hardhat with Chainlink](https://blog.chain.link/using-chainlink-with-hardhat/).
```

2022-03-21 02:53 UTC, dwightjl commented on docs/Developer Reference/create-a-chainlinked-project.md
> +For more details on how to use Chainlink with Brownie, see our blog post [Develop a DeFi Project Using Python](https://blog.chain.link/develop-python-defi-project/).
```suggestion
For more details on how to use Chainlink with Brownie, see the [Develop a DeFi Project Using Python](https://blog.chain.link/develop-python-defi-project/) blog post.
```

2022-03-21 02:53 UTC, dwightjl commented on docs/Developer Reference/create-a-chainlinked-project.md
>  For more details on how to use Chainlink with Truffle, see our blog post [Using Truffle to interact with Chainlink Smart Contracts](https://www.trufflesuite.com/blog/using-truffle-to-interact-with-ch
```suggestion
For more details on how to use Chainlink with Truffle, see our blog post about [Using Truffle to interact with Chainlink Smart Contracts](https://www.trufflesuite.com/blog/using-truffle-to-interact-with-chainlink-smart-contracts).
```

2022-03-21 02:53 UTC, dwightjl commented on docs/Developer Reference/create-a-chainlinked-project.md
> +For more details on how to use Chainlink with DappTools, see our blog post [How To Use DappTools](https://blog.chain.link/how-to-use-dapptools/).
```suggestion
For more details on how to use Chainlink with DappTools, see the [How To Use DappTools](https://blog.chain.link/how-to-use-dapptools/) blog post.
```

2022-03-21 02:54 UTC, dwightjl approved these changes

2022-03-21 02:58 UTC, merged