Added missing [mode] parameter.
smartcontractkit/documentation pull request #679
Opened 2022-03-29 08:19 UTC by pinebit

`cborparse` task has parameter "mode" which was undocumented.

2022-03-29 23:11 UTC, jmank88 approved these changes

2022-04-07 08:20 UTC, dwightjl requested changes

2022-04-07 08:20 UTC, dwightjl commented on docs/Oracle Jobs/Task Types/task_cborparse.md
> +- `mode`: optional string: `diet` (default) or `standard`. In `diet` mode, the incoming CBOR is expected to be a map.
```suggestion
- `data`: A byte array containing the CBOR payload.
- `mode`: An optional parameter that specifies how to parse the incoming CBOR. The default mode is `diet`, which expects the input to be a map. Set the mode to `standard` to pass literal values through "as-is". Empty inputs return nil.
```

Expanded the text based on the code comments here: https://github.com/smartcontractkit/chainlink/blob/d39dc15baddafb193b8919102bf8519c789f9083/core/cbor/cbor.go#L38

2022-04-07 08:21 UTC, dwightjl approved these changes

2022-04-07 08:34 UTC, merged