Update Getting Started VRF tutorial from v1 to v2
smartcontractkit/documentation pull request #689
Opened 2022-04-05 09:17 UTC by aelmanaa

2022-04-06 07:11 UTC, dwightjl requested changes
Works great! Just a few edits.

2022-04-06 07:11 UTC, dwightjl commented on docs/Introduction/tutorials/intermediates-tutorial.md
> +![Remix contract parameters to deploy](/files/intermediates-tutorial-02.png)
You might want to scale some of the larger images down a little bit if you have time.

2022-04-06 07:11 UTC, dwightjl commented on docs/Introduction/tutorials/intermediates-tutorial.md
> +You will have to wait a few minutes for your transaction to confirm and the response to be sent back. You can get your house by clicking the `house` function button with the address passed in `rollDi
```suggestion
You will have to wait a few minutes for your transaction to confirm and the response to be sent back. You can get your house by clicking the `house` function button with the address passed in `rollDice`. After the response is sent back, you'll be assigned a _Game of Thrones_ house!
```

2022-04-06 07:11 UTC, dwightjl commented on docs/Introduction/tutorials/intermediates-tutorial.md
> +After you open the deployed contract tab in the bottom left, the function buttons are available. Find `rollDice` and click the caret to expand the parameter fields. Enter an Ethereum address, and cli
```suggestion
After you open the deployed contract tab in the bottom left, the function buttons are available. Find `rollDice` and click the caret to expand the parameter fields. Enter an Ethereum address to specify a "dice roller", and click 'rollDice'.
```

2022-04-06 08:18 UTC, aelmanaa commented on _includes/samples/VRF/VRFD20.sol
> + * of a 20 sided dice
ok thanks , I learnt something :)

2022-04-07 07:50 UTC, dwightjl approved these changes

2022-04-07 07:52 UTC, merged