Fix large job example
smartcontractkit/documentation pull request #720
Opened 2022-04-20 08:29 UTC by aelmanaa

Fix Connect any API [large job example](https://docs.chain.link/docs/large-responses/)

2022-04-21 07:05 UTC, dwightjl requested changes

2022-04-21 07:08 UTC, dwightjl commented on docs/Using Any API/large-responses.md
>  The job spec for the Chainlink node in this example can be [found here](../example-job-spec-large/).
Ignore. I see we have the update in https://github.com/smartcontractkit/documentation/pull/673/files

2022-04-21 09:35 UTC, aelmanaa commented on docs/Using Any API/large-responses.md
>  `oracle` refers to a specific Chainlink node that a contract makes an API call from, and `specId` refers to a specific job for that node to run. Each job is unique and returns different types of data
good catch! solved

2022-04-25 05:37 UTC, dwightjl requested changes

2022-04-25 05:37 UTC, dwightjl commented on docs/Using Any API/large-responses.md
>  {% include 'samples/APIRequests/GenericBigWord.sol' %}
Add instructions for how to test this example.

2022-04-25 05:37 UTC, dwightjl commented on docs/Using Any API/large-responses.md
> +## Choosing Link token address, Oracle and JobId
```suggestion
## Setting the LINK token address, Oracle, and JobId
```

2022-04-25 09:17 UTC, closed without merging