Any API - Correct multiword examples
smartcontractkit/documentation pull request #721
Opened 2022-04-20 11:00 UTC by aelmanaa

Fix https://docs.chain.link/docs/multi-variable-responses/

2022-04-21 07:06 UTC, dwightjl requested changes

2022-04-21 09:15 UTC, aelmanaa commented on yarn.lock
Once I rebased, a new _yarn.lock_ was generated once I ran _yarn install_ .  No changes to _package.json_

2022-04-25 05:34 UTC, dwightjl requested changes

2022-04-25 05:34 UTC, dwightjl commented on docs/Using Any API/multi-variable-responses.md
> +## Choosing Link token address, Oracle and JobId
```suggestion
## Setting the LINK token address, Oracle, and JobId
```

2022-04-25 05:34 UTC, dwightjl commented on docs/Using Any API/multi-variable-responses.md
>  {% include 'samples/APIRequests/MultiWordConsumer.sol' %}
Add some steps to make this example work.

2022-04-25 05:34 UTC, dwightjl commented on yarn.lock
Rebase to main and try it again? I'm not getting any changes on main right now. It seems like the registry URL is changing as well.

2022-04-25 07:38 UTC, closed without merging