Update keeper.md
smartcontractkit/documentation pull request #732
Opened 2022-04-26 05:42 UTC by wentzeld

Updated job spec to match latest version

2022-04-26 10:45 UTC, infiloop2 approved these changes

2022-04-27 08:01 UTC, dwightjl requested changes

2022-04-27 08:01 UTC, dwightjl commented on docs/Oracle Jobs/Job Types/keeper.md
> +observationSource = """
I tested this on a 1.3.0 node and something is wrong with the observationSource. I keep getting a `invalid observation source provided` error when I try to create the job even though the task list looks correct. I made a few changes to improve syntax highlighting but couldn't figure out what was preventing this job from being created.

2022-05-02 06:25 UTC, dwightjl approved these changes
Tested on 1.4.0

2022-05-02 06:28 UTC, merged