Update AWS best practice page
smartcontractkit/documentation pull request #736
Opened 2022-05-01 23:52 UTC by ritika-b

- Fixes part of #716 
- Updates organization and formatting
- Adds pricing links to AWS services

TODO
- Add copy/paste functionality to code snippets
- Add more/amended recommendations
- Add TOC and better overview

2022-05-20 15:42 UTC, dwightjl requested changes
LGTM after a few writer edits

2022-05-20 15:42 UTC, dwightjl commented on docs/Node Operators/best-practices-aws.md
> +In the AWS console, if the **SSL certificate with AWS Certificate Manager** is set to `false`, we can leave **arn:aws:acm:region:account-id:certificate** as is. However, if you would like your node t
```suggestion
In the AWS console, if the **SSL certificate with AWS Certificate Manager** is set to `false`, you can leave **arn:aws:acm:region:account-id:certificate** as is. However, if your node is external facing and must be reached by the internet, enable this feature and set it to `true`.
```

2022-05-20 15:42 UTC, dwightjl commented on docs/Node Operators/best-practices-aws.md
> +In the AWS console, if the **Amazon DevOps Guru** is set to `false`, we can leave **AdministerAccountId** and **EmailAddress** as is.
```suggestion
In the AWS console, if the **Amazon DevOps Guru** is set to `false`, you can leave **AdministerAccountId** and **EmailAddress** as is. 
```

2022-05-23 19:23 UTC, dangitsdavid approved these changes

2022-05-24 00:14 UTC, dwightjl approved these changes

2022-05-24 00:18 UTC, merged