Update keepers-release-notes.md
smartcontractkit/documentation pull request #902
Opened 2022-08-05 20:02 UTC by wentzeld

**IMPORTANT: Please do not create a Pull Request without creating an issue first.Any change needs to be discussed before proceeding.**

## Closing issues

closes #901

...

## Description
Improves Keeper minimum spending amount wording

...

## Changes

- High level
- changes that
- you made
- ...

2022-08-05 21:59 UTC, ritika-b approved these changes

2022-08-08 05:46 UTC, dwightjl requested changes

2022-08-08 05:46 UTC, dwightjl commented on docs/chainlink-keepers/keepers-release-notes.md
> +- **Minimum spend requirement**: As part of the mission to continuously enhance the security of the Chainlink Network for all participants, each registered Upkeep will have a minimum spend requiremen
```suggestion
- **Minimum spend requirement**: As part of the mission to continuously enhance the security of the Chainlink Network for all participants, each registered upkeep will have a minimum spend requirement of 0.1 LINK to discourage network spam. Note that an *upkeep* is the automation job itself. It is not a transaction. Each upkeep can have thousands of transactions. If an upkeep has not spent more than 0.1 LINK on transactions at the time of cancellation, then 0.1 LINK will be retained for the network. If more than 0.1 LINK has been spent by an upkeep, the full remaining balance of the upkeep will be withdrawable when the upkeep is canceled.
```

Upkeep should be lower-case unless it is a proper noun.

2022-08-08 05:48 UTC, dwightjl approved these changes

2022-08-08 05:50 UTC, merged