Chainlink Node Release Next
smartcontractkit/documentation pull request #926
Opened 2022-08-12 15:13 UTC by dwightjl

- hexencode and base64encode tasks: https://github.com/smartcontractkit/documentation/pull/909

2022-08-27 12:18 UTC, chainchad approved these changes
Small fix suggested but LGTM otherwise

2022-08-27 12:18 UTC, chainchad commented on docs/chainlink-nodes/configuration-variables.md
> +Controls controls node picking strategy. Supported values:
```suggestion
Controls node picking strategy. Supported values:
```

2022-08-29 07:20 UTC, aelmanaa requested changes

2022-08-29 07:20 UTC, aelmanaa commented on docs/chainlink-nodes/node-versions.md
> +- `forwardingAllowed` per job attribute to allow forwarding txs submitted by the job.
```suggestion
- Added the `hexencode` and `base64encode` tasks (pipeline). See the [Hex Encode Task](/docs/jobs/task-types/hexencode/) and [Base64 Encode Task](/docs/jobs/task-types/base64encode/) pages for examples.
- `forwardingAllowed` per job attribute to allow forwarding txs submitted by the job.
```

2022-09-01 22:25 UTC, merged