Update product landing pages
smartcontractkit/documentation pull request #979
Opened 2022-09-01 15:35 UTC by ritika-b

- Updates all homepage titles to "Chainlink [product name] Documentation"
- Adds TOC to all pages (headlined Topics)
- Removes Overview section
- Updates subheadings to sentence-casing
- Adds video to each product landing page

2022-09-08 07:56 UTC, aelmanaa requested changes

2022-09-08 07:56 UTC, aelmanaa commented on docs/data-feeds/using-chainlink-reference-contracts.md
> +If you already have a project started and would like to integrate Chainlink, you can [add Chainlink to your existing project](../create-a-chainlinked-project/#install-into-existing-projects) by using
```suggestion
If you already have a project started and would like to integrate Chainlink, you can [add Chainlink to your existing project](../create-a-chainlinked-project/#install-into-existing-projects) by using the [`@chainlink/contracts` NPM package](https://www.npmjs.com/package/@chainlink/contracts).
```

there are other chainlink packages out there. so better be specific

2022-09-11 18:27 UTC, dwightjl approved these changes

2022-09-11 18:46 UTC, dwightjl commented on docs/chainlink-keepers/introduction.md
> +- [Questions and examples](#questions-and-examples)
Let's stick with `-` characters for unordered lists. This is the default for the Prettier format as well.

2022-09-11 19:51 UTC, merged